#!/bin/sh
# File generated by ocamlbuild

cd '/home/adam/Desktop/4115 project/YAGL/4115_project'

rm -f yaglparse.ml
rm -f yaglparse.mli
# Also clean the script itself
rm -f '/home/adam/Desktop/4115 project/YAGL/4115_project/_build/sanitize.sh'
